name: squad
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10
  - cudnn=7.3.1
  - numpy=1
  - pip=19
  - python=3.7
  - pytorch=1
  - scipy=1
  - spacy=2.1
  - tensorboard
  - tensorboardx
  - tensorflow
  - tqdm=4
  - ujson=1
  - urllib3
